// Copyright (c) 2017, 2024, Oracle and/or its affiliates. All rights reserved.
// Licensed under the Mozilla Public License v2.0

package data_safe

import "github.com/oracle/terraform-provider-oci/internal/tfresource"

func RegisterResource() {
	tfresource.RegisterResource("oci_data_safe_alert", DataSafeAlertResource())
	tfresource.RegisterResource("oci_data_safe_alert_policy", DataSafeAlertPolicyResource())
	tfresource.RegisterResource("oci_data_safe_alert_policy_rule", DataSafeAlertPolicyRuleResource())
	tfresource.RegisterResource("oci_data_safe_audit_archive_retrieval", DataSafeAuditArchiveRetrievalResource())
	tfresource.RegisterResource("oci_data_safe_audit_policy", DataSafeAuditPolicyResource())
	tfresource.RegisterResource("oci_data_safe_audit_policy_management", DataSafeAuditPolicyManagementResource())
	tfresource.RegisterResource("oci_data_safe_audit_profile", DataSafeAuditProfileResource())
	tfresource.RegisterResource("oci_data_safe_audit_profile_management", DataSafeAuditProfileManagementResource())
	tfresource.RegisterResource("oci_data_safe_audit_trail", DataSafeAuditTrailResource())
	tfresource.RegisterResource("oci_data_safe_audit_trail_management", DataSafeAuditTrailManagementResource())
	tfresource.RegisterResource("oci_data_safe_calculate_audit_volume_available", DataSafeCalculateAuditVolumeAvailableResource())
	tfresource.RegisterResource("oci_data_safe_calculate_audit_volume_collected", DataSafeCalculateAuditVolumeCollectedResource())
	tfresource.RegisterResource("oci_data_safe_compare_security_assessment", DataSafeCompareSecurityAssessmentResource())
	tfresource.RegisterResource("oci_data_safe_compare_user_assessment", DataSafeCompareUserAssessmentResource())
	tfresource.RegisterResource("oci_data_safe_data_safe_configuration", DataSafeDataSafeConfigurationResource())
	tfresource.RegisterResource("oci_data_safe_data_safe_private_endpoint", DataSafeDataSafePrivateEndpointResource())
	tfresource.RegisterResource("oci_data_safe_database_security_config", DataSafeDatabaseSecurityConfigResource())
	tfresource.RegisterResource("oci_data_safe_database_security_config_management", DataSafeDatabaseSecurityConfigManagementResource())
	tfresource.RegisterResource("oci_data_safe_discovery_job", DataSafeDiscoveryJobResource())
	tfresource.RegisterResource("oci_data_safe_library_masking_format", DataSafeLibraryMaskingFormatResource())
	tfresource.RegisterResource("oci_data_safe_masking_policies_masking_column", DataSafeMaskingPoliciesMaskingColumnResource())
	tfresource.RegisterResource("oci_data_safe_masking_policy", DataSafeMaskingPolicyResource())
	tfresource.RegisterResource("oci_data_safe_on_prem_connector", DataSafeOnPremConnectorResource())
	tfresource.RegisterResource("oci_data_safe_masking_report_management", DataSafeMaskingReportManagementResource())
	tfresource.RegisterResource("oci_data_safe_masking_policy_health_report_management", DataSafeMaskingPolicyHealthReportManagementResource())
	tfresource.RegisterResource("oci_data_safe_report", DataSafeReportResource())
	tfresource.RegisterResource("oci_data_safe_report_definition", DataSafeReportDefinitionResource())
	tfresource.RegisterResource("oci_data_safe_sdm_masking_policy_difference", DataSafeSdmMaskingPolicyDifferenceResource())
	tfresource.RegisterResource("oci_data_safe_security_assessment", DataSafeSecurityAssessmentResource())
	tfresource.RegisterResource("oci_data_safe_security_policy", DataSafeSecurityPolicyResource())
	tfresource.RegisterResource("oci_data_safe_security_policy_deployment", DataSafeSecurityPolicyDeploymentResource())
	tfresource.RegisterResource("oci_data_safe_security_policy_deployment_management", DataSafeSecurityPolicyDeploymentManagementResource())
	tfresource.RegisterResource("oci_data_safe_security_policy_management", DataSafeSecurityPolicyManagementResource())
	tfresource.RegisterResource("oci_data_safe_sensitive_data_model", DataSafeSensitiveDataModelResource())
	tfresource.RegisterResource("oci_data_safe_sensitive_data_models_sensitive_column", DataSafeSensitiveDataModelsSensitiveColumnResource())
	tfresource.RegisterResource("oci_data_safe_sensitive_type", DataSafeSensitiveTypeResource())
	tfresource.RegisterResource("oci_data_safe_set_security_assessment_baseline_management", DataSafeSetSecurityAssessmentBaselineManagementResource())
	tfresource.RegisterResource("oci_data_safe_set_security_assessment_baseline", DataSafeSetSecurityAssessmentBaselineResource())
	tfresource.RegisterResource("oci_data_safe_set_user_assessment_baseline", DataSafeSetUserAssessmentBaselineResource())
	tfresource.RegisterResource("oci_data_safe_set_user_assessment_baseline_management", DataSafeSetUserAssessmentBaselineManagementResource())
	tfresource.RegisterResource("oci_data_safe_sql_collection", DataSafeSqlCollectionResource())
	tfresource.RegisterResource("oci_data_safe_sql_firewall_policy", DataSafeSqlFirewallPolicyResource())
	tfresource.RegisterResource("oci_data_safe_sql_firewall_policy_management", DataSafeSqlFirewallPolicyManagementResource())
	tfresource.RegisterResource("oci_data_safe_target_alert_policy_association", DataSafeTargetAlertPolicyAssociationResource())
	tfresource.RegisterResource("oci_data_safe_target_database", DataSafeTargetDatabaseResource())
	tfresource.RegisterResource("oci_data_safe_target_database_peer_target_database", DataSafeTargetDatabasePeerTargetDatabaseResource())
	tfresource.RegisterResource("oci_data_safe_unset_security_assessment_baseline_management", DataSafeUnsetSecurityAssessmentBaselineManagementResource())
	tfresource.RegisterResource("oci_data_safe_unset_security_assessment_baseline", DataSafeUnsetSecurityAssessmentBaselineResource())
	tfresource.RegisterResource("oci_data_safe_unset_user_assessment_baseline", DataSafeUnsetUserAssessmentBaselineResource())
	tfresource.RegisterResource("oci_data_safe_unset_user_assessment_baseline_management", DataSafeUnsetUserAssessmentBaselineManagementResource())
	tfresource.RegisterResource("oci_data_safe_user_assessment", DataSafeUserAssessmentResource())
	tfresource.RegisterResource("oci_data_safe_mask_data", DataSafeMaskDataResource())
	tfresource.RegisterResource("oci_data_safe_add_sdm_columns", DataSafeAddColumnsFromSdmResource())
	tfresource.RegisterResource("oci_data_safe_sensitive_data_models_apply_discovery_job_results", DataSafeSensitiveDataModelsApplyDiscoveryJobResultsResource())
	tfresource.RegisterResource("oci_data_safe_masking_policies_apply_difference_to_masking_columns", DataSafeMaskingPolicyApplyDifferenceToMaskingColumnsResource())
	tfresource.RegisterResource("oci_data_safe_discovery_jobs_result", DataSafeDiscoveryJobsResultResource())
}
