## This configuration was generated by terraform-provider-oci

resource oci_datascience_notebook_session export_test_project_data_science_session {
  compartment_id = var.compartment_ocid
  defined_tags = {
  }
  display_name = "test_project_data_science_session"
  freeform_tags = {
    "delete" = "true"
  }
  notebook_session_config_details {
    block_storage_size_in_gbs = "100"
    notebook_session_shape_config_details {
      memory_in_gbs = "16"
      ocpus         = "1"
    }
    shape = "VM.Standard.E4.Flex"
    #subnet_id = <<Optional value not found in discovery>>
  }
  project_id = oci_datascience_project.export_test_project_data_science.id
  state      = "ACTIVE"
}

resource oci_datascience_project export_test_project_data_science {
  compartment_id = var.compartment_ocid
  defined_tags = {
  }
  #description = <<Optional value not found in discovery>>
  display_name = "test_project_data_science"
  freeform_tags = {
    "delete" = "true"
  }
}

