## This configuration was generated by terraform-provider-oci

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220621152334 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220621152334"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

