// Copyright (c) 2017, 2024, Oracle and/or its affiliates. All rights reserved.
// Licensed under the Mozilla Public License v2.0

package os_management_hub

import "github.com/oracle/terraform-provider-oci/internal/tfresource"

func RegisterResource() {
	tfresource.RegisterResource("oci_os_management_hub_event", OsManagementHubEventResource())
	tfresource.RegisterResource("oci_os_management_hub_lifecycle_environment", OsManagementHubLifecycleEnvironmentResource())
	tfresource.RegisterResource("oci_os_management_hub_lifecycle_stage_attach_managed_instances_management", OsManagementHubLifecycleStageAttachManagedInstancesManagementResource())
	tfresource.RegisterResource("oci_os_management_hub_lifecycle_stage_detach_managed_instances_management", OsManagementHubLifecycleStageDetachManagedInstancesManagementResource())
	tfresource.RegisterResource("oci_os_management_hub_lifecycle_stage_promote_software_source_management", OsManagementHubLifecycleStagePromoteSoftwareSourceManagementResource())
	tfresource.RegisterResource("oci_os_management_hub_managed_instance", OsManagementHubManagedInstanceResource())
	tfresource.RegisterResource("oci_os_management_hub_managed_instance_attach_profile_management", OsManagementHubManagedInstanceAttachProfileManagementResource())
	tfresource.RegisterResource("oci_os_management_hub_managed_instance_detach_profile_management", OsManagementHubManagedInstanceDetachProfileManagementResource())
	tfresource.RegisterResource("oci_os_management_hub_managed_instance_group", OsManagementHubManagedInstanceGroupResource())
	tfresource.RegisterResource("oci_os_management_hub_managed_instance_group_attach_managed_instances_management", OsManagementHubManagedInstanceGroupAttachManagedInstancesManagementResource())
	tfresource.RegisterResource("oci_os_management_hub_managed_instance_group_attach_software_sources_management", OsManagementHubManagedInstanceGroupAttachSoftwareSourcesManagementResource())
	tfresource.RegisterResource("oci_os_management_hub_managed_instance_group_detach_managed_instances_management", OsManagementHubManagedInstanceGroupDetachManagedInstancesManagementResource())
	tfresource.RegisterResource("oci_os_management_hub_managed_instance_group_detach_software_sources_management", OsManagementHubManagedInstanceGroupDetachSoftwareSourcesManagementResource())
	tfresource.RegisterResource("oci_os_management_hub_managed_instance_group_install_packages_management", OsManagementHubManagedInstanceGroupInstallPackagesManagementResource())
	tfresource.RegisterResource("oci_os_management_hub_managed_instance_group_install_windows_updates_management", OsManagementHubManagedInstanceGroupInstallWindowsUpdatesManagementResource())
	tfresource.RegisterResource("oci_os_management_hub_managed_instance_group_manage_module_streams_management", OsManagementHubManagedInstanceGroupManageModuleStreamsManagementResource())
	tfresource.RegisterResource("oci_os_management_hub_managed_instance_group_remove_packages_management", OsManagementHubManagedInstanceGroupRemovePackagesManagementResource())
	tfresource.RegisterResource("oci_os_management_hub_managed_instance_group_update_all_packages_management", OsManagementHubManagedInstanceGroupUpdateAllPackagesManagementResource())
	tfresource.RegisterResource("oci_os_management_hub_managed_instance_install_windows_updates_management", OsManagementHubManagedInstanceInstallWindowsUpdatesManagementResource())
	tfresource.RegisterResource("oci_os_management_hub_managed_instance_update_packages_management", OsManagementHubManagedInstanceUpdatePackagesManagementResource())
	tfresource.RegisterResource("oci_os_management_hub_management_station", OsManagementHubManagementStationResource())
	tfresource.RegisterResource("oci_os_management_hub_management_station_mirror_synchronize_management", OsManagementHubManagementStationMirrorSynchronizeManagementResource())
	tfresource.RegisterResource("oci_os_management_hub_management_station_refresh_management", OsManagementHubManagementStationRefreshManagementResource())
	tfresource.RegisterResource("oci_os_management_hub_management_station_synchronize_mirrors_management", OsManagementHubManagementStationSynchronizeMirrorsManagementResource())
	tfresource.RegisterResource("oci_os_management_hub_profile", OsManagementHubProfileResource())
	tfresource.RegisterResource("oci_os_management_hub_scheduled_job", OsManagementHubScheduledJobResource())
	tfresource.RegisterResource("oci_os_management_hub_software_source", OsManagementHubSoftwareSourceResource())
	tfresource.RegisterResource("oci_os_management_hub_software_source_add_packages_management", OsManagementHubSoftwareSourceAddPackagesManagementResource())
	tfresource.RegisterResource("oci_os_management_hub_software_source_change_availability_management", OsManagementHubSoftwareSourceChangeAvailabilityManagementResource())
}
