#!/bin/bash
set -e

## Install and configure a NFS server to export a 2TB remote attached LUN.
yum update -y

### Storage setup
wget -O /usr/local/bin/iscsiattach.sh https://raw.githubusercontent.com/oracle/terraform-provider-baremetal/master/docs/examples/storage/nfs/userdata/nfs-bootstrap
chmod +x /usr/local/bin/iscsiattach.sh
/usr/local/bin/iscsiattach.sh
mkfs.xfs /dev/sdb
mkdir /mnt/2tb-nfs
mount -t xfs /dev/sdb /mnt/2tb-nfs/

### NFS setup
firewall-cmd --permanent --zone=public --add-service=nfs
yum -y install nfs-utils
systemctl enable nfs-server.service
systemctl start nfs-server.service
chown nfsnobody:nfsnobody /mnt/2tb-nfs/
chmod 755 /mnt/2tb-nfs/
cidr=`ip addr show dev ens3 | grep "inet " | awk -F' ' '{print $2}'`
echo "/mnt/2tb-nfs $cidr(rw,sync,no_subtree_check)" > /etc/exports
exportfs -a
