## This configuration was generated by terraform-provider-oci

resource oci_database_cloud_vm_cluster export_dbsystem20230228052513 {
  backup_network_nsg_ids = [
    "ocid1.networksecuritygroup.oc1.iad.aaaaaaaac57yx27jgnlwpqtcv43zt3rotwd2k3iyx7edinsnx3xno3ul25bq",
  ]
  backup_subnet_id                = "ocid1.subnet.oc1.iad.aaaaaaaadaoqc7ee5lhus4orcm3ov4cnad2jqyi7xtezveyyw5hps3r3qn5q"
  cloud_exadata_infrastructure_id = oci_database_cloud_exadata_infrastructure.export_cloudexadatainfrastructure20230228052748.id
  cluster_name                    = "cl-4cf5uwca"
  compartment_id                  = var.compartment_ocid
  cpu_core_count                  = "22"
  #create_async = <<Optional value not found in discovery>>
  data_storage_percentage = "80"
  #data_storage_size_in_tbs = <<Optional value not found in discovery>>
  #db_node_storage_size_in_gbs = <<Optional value not found in discovery>>
  db_servers = [
  ]
  defined_tags = {
  }
  display_name = "dbsystem20230228052513"
  domain       = "subnetexadata1.tfvcn.oraclevcn.com"
  freeform_tags = {
  }
  gi_version                  = "19.9.0.0.0"
  hostname                    = "myoracledb-xwuy7"
  is_local_backup_enabled     = "false"
  is_sparse_diskgroup_enabled = "false"
  license_model               = "LICENSE_INCLUDED"
  memory_size_in_gbs          = "1440"
  nsg_ids = [
    "ocid1.networksecuritygroup.oc1.iad.aaaaaaaa5yfatyjw4h6egnc7qlsw5am57uqbxwmosau4v43vtyojodrdhbfa",
  ]
  ocpu_count = "22"
  #private_zone_id = <<Optional value not found in discovery>>
  scan_listener_port_tcp     = "1521"
  scan_listener_port_tcp_ssl = "2484"
  ssh_public_keys = [
    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOuBJgh6lTmQvQJ4BA3RCJdSmxRtmiXAQEEIP68/G4gF3XuZdKEYTFeputacmRq9yO5ZnNXgO9akdUgePpf8+CfFtveQxmN5xo3HVCDKxu/70lbMgeu7+wJzrMOlzj+a4zNq2j0Ww2VWMsisJ6eV3bJTnO/9VLGCOC8M9noaOlcKcLgIYy4aDM724MxFX2lgn7o6rVADHRxkvLEXPVqYT4syvYw+8OVSnNgE4MJLxaw8/2K0qp19YlQyiriIXfQpci3ThxwLjymYRPj+kjU1xIxv6qbFQzHR7ds0pSWp1U06cIoKPfCazU9hGWW8yIe/vzfTbWrt2DK6pLwBn/G0x3 sample",
  ]
  subnet_id = "ocid1.subnet.oc1.iad.aaaaaaaakuiaelgnu4kxsykwy3sfbkg54nbqiyq4mfa3ysnqlmvq2tesrunq"
  time_zone = "US/Pacific"
}

resource oci_database_cloud_vm_cluster export_dbsystem20230225052029 {
  backup_network_nsg_ids = [
    "ocid1.networksecuritygroup.oc1.iad.aaaaaaaayky36iwu55bq3npndvy7k2h2n5zxxe2mz5tyjmsejfpnnxramqzq",
  ]
  backup_subnet_id                = "ocid1.subnet.oc1.iad.aaaaaaaaskmjobjshq2uuhgnasexeruzk6h72ppbne56ypiilvipm4lqtpza"
  cloud_exadata_infrastructure_id = oci_database_cloud_exadata_infrastructure.export_cloudexadatainfrastructure20230225052245.id
  cluster_name                    = "cl-ihgbbiya"
  compartment_id                  = var.compartment_ocid
  cpu_core_count                  = "22"
  #create_async = <<Optional value not found in discovery>>
  data_storage_percentage = "80"
  #data_storage_size_in_tbs = <<Optional value not found in discovery>>
  #db_node_storage_size_in_gbs = <<Optional value not found in discovery>>
  db_servers = [
  ]
  defined_tags = {
  }
  display_name = "dbsystem20230225052029"
  domain       = "subnetexadata1.tfvcn.oraclevcn.com"
  freeform_tags = {
  }
  gi_version                  = "19.9.0.0.0"
  hostname                    = "myoracledb-m65lj"
  is_local_backup_enabled     = "false"
  is_sparse_diskgroup_enabled = "false"
  license_model               = "LICENSE_INCLUDED"
  memory_size_in_gbs          = "1440"
  nsg_ids = [
    "ocid1.networksecuritygroup.oc1.iad.aaaaaaaalcexovowpp2s3zqtfyafff5citruzdzfzrjvyeqvlklpe3ky6dva",
  ]
  ocpu_count = "22"
  #private_zone_id = <<Optional value not found in discovery>>
  scan_listener_port_tcp     = "1521"
  scan_listener_port_tcp_ssl = "2484"
  ssh_public_keys = [
    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOuBJgh6lTmQvQJ4BA3RCJdSmxRtmiXAQEEIP68/G4gF3XuZdKEYTFeputacmRq9yO5ZnNXgO9akdUgePpf8+CfFtveQxmN5xo3HVCDKxu/70lbMgeu7+wJzrMOlzj+a4zNq2j0Ww2VWMsisJ6eV3bJTnO/9VLGCOC8M9noaOlcKcLgIYy4aDM724MxFX2lgn7o6rVADHRxkvLEXPVqYT4syvYw+8OVSnNgE4MJLxaw8/2K0qp19YlQyiriIXfQpci3ThxwLjymYRPj+kjU1xIxv6qbFQzHR7ds0pSWp1U06cIoKPfCazU9hGWW8yIe/vzfTbWrt2DK6pLwBn/G0x3 sample",
  ]
  subnet_id = "ocid1.subnet.oc1.iad.aaaaaaaaarlayrd4z367ctsmhnnj2r7w5qci23f42j553nwzlqh26j47wqaa"
  time_zone = "US/Pacific"
}

resource oci_database_cloud_vm_cluster export_dbsystem20220322041338 {
  backup_network_nsg_ids = [
    "ocid1.networksecuritygroup.oc1.iad.aaaaaaaawryxqo76fzzlx6one37e5sd6nuawquqhp4earnyiyuy7a5tienra",
  ]
  backup_subnet_id                = "ocid1.subnet.oc1.iad.aaaaaaaa4dtby62756swlnjaxuuhhtxnrmty4x4cfrjcpdpowhi7npwpn4wa"
  cloud_exadata_infrastructure_id = oci_database_cloud_exadata_infrastructure.export_cloudexadatainfrastructure20220322041458.id
  cluster_name                    = "cl-fx7osmba"
  compartment_id                  = var.compartment_ocid
  cpu_core_count                  = "22"
  #create_async = <<Optional value not found in discovery>>
  data_storage_percentage = "80"
  #data_storage_size_in_tbs = <<Optional value not found in discovery>>
  #db_node_storage_size_in_gbs = <<Optional value not found in discovery>>
  db_servers = [
  ]
  defined_tags = {
  }
  display_name = "dbsystem20220322041338"
  domain       = "subnetexadata1.tfvcn.oraclevcn.com"
  freeform_tags = {
  }
  gi_version                  = "19.9.0.0.0"
  hostname                    = "myoracledb-79gab"
  is_local_backup_enabled     = "false"
  is_sparse_diskgroup_enabled = "false"
  license_model               = "LICENSE_INCLUDED"
  memory_size_in_gbs          = "1440"
  nsg_ids = [
    "ocid1.networksecuritygroup.oc1.iad.aaaaaaaaarliuy4uqcn5qvtzq6gzwq4tv3aiw5a6akwagxl4beloffibigbq",
  ]
  ocpu_count = "22"
  #private_zone_id = <<Optional value not found in discovery>>
  scan_listener_port_tcp     = "1521"
  scan_listener_port_tcp_ssl = "2484"
  ssh_public_keys = [
    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOuBJgh6lTmQvQJ4BA3RCJdSmxRtmiXAQEEIP68/G4gF3XuZdKEYTFeputacmRq9yO5ZnNXgO9akdUgePpf8+CfFtveQxmN5xo3HVCDKxu/70lbMgeu7+wJzrMOlzj+a4zNq2j0Ww2VWMsisJ6eV3bJTnO/9VLGCOC8M9noaOlcKcLgIYy4aDM724MxFX2lgn7o6rVADHRxkvLEXPVqYT4syvYw+8OVSnNgE4MJLxaw8/2K0qp19YlQyiriIXfQpci3ThxwLjymYRPj+kjU1xIxv6qbFQzHR7ds0pSWp1U06cIoKPfCazU9hGWW8yIe/vzfTbWrt2DK6pLwBn/G0x3 sample",
  ]
  subnet_id = "ocid1.subnet.oc1.iad.aaaaaaaa75j3jjkxpeauhza5nkv7by5ghidvjodmzenfjmqoxiqgrom7un4a"
  time_zone = "US/Pacific"
}

resource oci_database_cloud_vm_cluster export_dbsystem20220315041741 {
  backup_network_nsg_ids = [
    "ocid1.networksecuritygroup.oc1.iad.aaaaaaaaz6fkkut5rkr5rmcs6ubkw2l2zxfqd7fulmyufzk36uhhbhlrfuhq",
  ]
  backup_subnet_id                = "ocid1.subnet.oc1.iad.aaaaaaaallr2el2mazqjpfbr6aygdtb7eff56irn6pzr3f7g2jmgofwwnvla"
  cloud_exadata_infrastructure_id = oci_database_cloud_exadata_infrastructure.export_cloudexadatainfrastructure20220315041916.id
  cluster_name                    = "cl-64qvy3ga"
  compartment_id                  = var.compartment_ocid
  cpu_core_count                  = "22"
  #create_async = <<Optional value not found in discovery>>
  data_storage_percentage = "80"
  #data_storage_size_in_tbs = <<Optional value not found in discovery>>
  #db_node_storage_size_in_gbs = <<Optional value not found in discovery>>
  db_servers = [
  ]
  defined_tags = {
  }
  display_name = "dbsystem20220315041741"
  domain       = "subnetexadata1.tfvcn.oraclevcn.com"
  freeform_tags = {
  }
  gi_version                  = "19.9.0.0.0"
  hostname                    = "myoracledb-iho5s"
  is_local_backup_enabled     = "false"
  is_sparse_diskgroup_enabled = "false"
  license_model               = "LICENSE_INCLUDED"
  memory_size_in_gbs          = "1440"
  nsg_ids = [
    "ocid1.networksecuritygroup.oc1.iad.aaaaaaaafyh4d6md4y4xupwtj6lvjxayd7pr3etjuisd7umq3jqa45lv6dcq",
  ]
  ocpu_count = "22"
  #private_zone_id = <<Optional value not found in discovery>>
  scan_listener_port_tcp     = "1521"
  scan_listener_port_tcp_ssl = "2484"
  ssh_public_keys = [
    "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOuBJgh6lTmQvQJ4BA3RCJdSmxRtmiXAQEEIP68/G4gF3XuZdKEYTFeputacmRq9yO5ZnNXgO9akdUgePpf8+CfFtveQxmN5xo3HVCDKxu/70lbMgeu7+wJzrMOlzj+a4zNq2j0Ww2VWMsisJ6eV3bJTnO/9VLGCOC8M9noaOlcKcLgIYy4aDM724MxFX2lgn7o6rVADHRxkvLEXPVqYT4syvYw+8OVSnNgE4MJLxaw8/2K0qp19YlQyiriIXfQpci3ThxwLjymYRPj+kjU1xIxv6qbFQzHR7ds0pSWp1U06cIoKPfCazU9hGWW8yIe/vzfTbWrt2DK6pLwBn/G0x3 sample",
  ]
  subnet_id = "ocid1.subnet.oc1.iad.aaaaaaaa5rbvna4keovcvcwzejz7fhhcz3sg54j2j2nuxdx3yaukzxowqxcq"
  time_zone = "US/Pacific"
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220104052318 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220104052318"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220402103804 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220402103804"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20211225051845 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20211225051845"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220809041353 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220809041353"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220305223701 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220305223701"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220709041547 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220709041547"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220219051647 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220219051647"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220102183502 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220102183502"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20230228052748 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20230228052748"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220510041400 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220510041400"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220115051728 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220115051728"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220430041417 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220430041417"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220315041916 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220315041916"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20211214051702 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20211214051702"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220302151115 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220302151115"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220111051755 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220111051755"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220426041644 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220426041644"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220222032505 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220222032505"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220719041718 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220719041718"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20211207051736 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20211207051736"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220920042826 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220920042826"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20211215010626 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20211215010626"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20211221051628 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20211221051628"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220206162613 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220206162613"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220621152334 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220621152334"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220723041609 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220723041609"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220412042011 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220412042011"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220524041547 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220524041547"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220205051246 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220205051246"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220217234144 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220217234144"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220305051320 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220305051320"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220118051516 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220118051516"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220129051549 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220129051549"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20211211051706 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20211211051706"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20221115052138 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20221115052138"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220219001115 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220219001115"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20211202212050 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20211202212050"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220418122408 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220418122408"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220503041731 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220503041731"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220112084007 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220112084007"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220108051758 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220108051758"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20211218053949 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20211218053949"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220306194127 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220306194127"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220826235310 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220826235310"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220309034203 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220309034203"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220127000034 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220127000034"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220702041746 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220702041746"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220122051712 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220122051712"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220319041718 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220319041718"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220514041347 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220514041347"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220208051716 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220208051716"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220625041649 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220625041649"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220621041851 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220621041851"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220621154509 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220621154509"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20230225052245 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20230225052245"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20211207173837 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20211207173837"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220118215251 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220118215251"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220411235409 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220411235409"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220806041713 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220806041713"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220416041656 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220416041656"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20211218051613 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20211218051613"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220129205314 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220129205314"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20211204051548 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20211204051548"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220225020203 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220225020203"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220308052115 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220308052115"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220201053839 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220201053839"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220125052011 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220125052011"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220322041458 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220322041458"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220205184642 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220205184642"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20211231130035 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20211231130035"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220604041651 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220604041651"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20211207201935 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20211207201935"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220208213402 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220208213402"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220315225222 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220315225222"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220217180333 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220217180333"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220507041309 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220507041309"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20211228053652 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20211228053652"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220113232935 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220113232935"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20211201005855 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20211201005855"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220301051327 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220301051327"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220204024707 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220204024707"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220204030506 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220204030506"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220827001559 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220827001559"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220104221557 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220104221557"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20221022042039 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20221022042039"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220205055547 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220205055547"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220517041608 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220517041608"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220802041936 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220802041936"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_cloud_exadata_infrastructure export_cloudexadatainfrastructure20220607041603 {
  availability_domain = var.availability_domain--LOil-US-ASHBURN-AD-3
  compartment_id      = var.compartment_ocid
  #compute_count = <<Optional value not found in discovery>>
  defined_tags = {
  }
  display_name = "cloudexadatainfrastructure20220607041603"
  freeform_tags = {
  }
  maintenance_window {
    custom_action_timeout_in_mins = "0"
    hours_of_day = [
    ]
    is_custom_action_timeout_enabled = "false"
    #is_monthly_patching_enabled = <<Optional value not found in discovery>>
    #lead_time_in_weeks = <<Optional value not found in discovery>>
    patching_mode = "ROLLING"
    preference    = "NO_PREFERENCE"
    weeks_of_month = [
    ]
  }
  shape = "Exadata.Quarter1.84"
  #storage_count = <<Optional value not found in discovery>>
}

resource oci_database_db_home export_dbhome20230228052513 {
  #database = <<Optional value not found in discovery>>
  #database_software_image_id = <<Optional value not found in discovery>>
  #db_system_id = <<Optional value not found in discovery>>
  db_version = "12.1.0.2"
  defined_tags = {
    "example-tag-namespace-all.example-tag" = "value"
  }
  display_name = "dbhome20230228052513"
  freeform_tags = {
    "Department" = "Finance"
  }
  #is_desupported_version = <<Optional value not found in discovery>>
  #kms_key_id = <<Optional value not found in discovery>>
  #kms_key_version_id = <<Optional value not found in discovery>>
  source        = "NONE"
  vm_cluster_id = oci_database_cloud_vm_cluster.export_dbsystem20230228052513.id
}

resource oci_database_database export_dbhome20230228052513_database {
  database {
    admin_password = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
    #backup_id = <<Optional value not found in discovery>>
    #backup_tde_password = <<Optional value not found in discovery>>
    character_set = "AL32UTF8"
    #database_software_image_id = <<Optional value not found in discovery>>
    #db_backup_config = <<Optional value not found in discovery>>
    db_name        = "aTFdb"
    db_unique_name = "aTFdb_7sc_iad"
    db_workload    = "OLTP"
    defined_tags = {
      "example-tag-namespace-all.example-tag" = "value"
    }
    freeform_tags = {
      "Department" = "Finance"
    }
    #kms_key_id = <<Optional value not found in discovery>>
    #kms_key_version_id = <<Optional value not found in discovery>>
    ncharacter_set = "AL16UTF16"
    #pdb_name = <<Optional value not found in discovery>>
    sid_prefix = "aTFdb"
    #tde_wallet_password = <<Optional value not found in discovery>>
    #vault_id = <<Optional value not found in discovery>>
  }
  db_home_id = oci_database_db_home.export_dbhome20230228052513.id
  #db_version = <<Optional value not found in discovery>>
  #kms_key_id = <<Optional value not found in discovery>>
  #kms_key_migration = <<Optional value not found in discovery>>
  #kms_key_rotation = <<Optional value not found in discovery>>
  #kms_key_version_id = <<Optional value not found in discovery>>
  source = "NONE" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  #vault_id = <<Optional value not found in discovery>>

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [database[0].admin_password, source]
  }
}

resource oci_database_db_home export_dbhome20230225052029 {
  #database = <<Optional value not found in discovery>>
  #database_software_image_id = <<Optional value not found in discovery>>
  #db_system_id = <<Optional value not found in discovery>>
  db_version = "12.1.0.2"
  defined_tags = {
    "example-tag-namespace-all.example-tag" = "value"
  }
  display_name = "dbhome20230225052029"
  freeform_tags = {
    "Department" = "Finance"
  }
  #is_desupported_version = <<Optional value not found in discovery>>
  #kms_key_id = <<Optional value not found in discovery>>
  #kms_key_version_id = <<Optional value not found in discovery>>
  source        = "NONE"
  vm_cluster_id = oci_database_cloud_vm_cluster.export_dbsystem20230225052029.id
}

resource oci_database_database export_dbhome20230225052029_database {
  database {
    admin_password = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
    #backup_id = <<Optional value not found in discovery>>
    #backup_tde_password = <<Optional value not found in discovery>>
    character_set = "AL32UTF8"
    #database_software_image_id = <<Optional value not found in discovery>>
    #db_backup_config = <<Optional value not found in discovery>>
    db_name        = "aTFdb"
    db_unique_name = "aTFdb_w4r_iad"
    db_workload    = "OLTP"
    defined_tags = {
      "example-tag-namespace-all.example-tag" = "value"
    }
    freeform_tags = {
      "Department" = "Finance"
    }
    #kms_key_id = <<Optional value not found in discovery>>
    #kms_key_version_id = <<Optional value not found in discovery>>
    ncharacter_set = "AL16UTF16"
    #pdb_name = <<Optional value not found in discovery>>
    sid_prefix = "aTFdb"
    #tde_wallet_password = <<Optional value not found in discovery>>
    #vault_id = <<Optional value not found in discovery>>
  }
  db_home_id = oci_database_db_home.export_dbhome20230225052029.id
  #db_version = <<Optional value not found in discovery>>
  #kms_key_id = <<Optional value not found in discovery>>
  #kms_key_migration = <<Optional value not found in discovery>>
  #kms_key_rotation = <<Optional value not found in discovery>>
  #kms_key_version_id = <<Optional value not found in discovery>>
  source = "NONE" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  #vault_id = <<Optional value not found in discovery>>

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [database[0].admin_password, source]
  }
}

resource oci_database_db_home export_dbhome20220322041338 {
  #database = <<Optional value not found in discovery>>
  #database_software_image_id = <<Optional value not found in discovery>>
  #db_system_id = <<Optional value not found in discovery>>
  db_version = "12.1.0.2"
  defined_tags = {
    "example-tag-namespace-all.example-tag" = "value"
  }
  display_name = "dbhome20220322041338"
  freeform_tags = {
    "Department" = "Finance"
  }
  #is_desupported_version = <<Optional value not found in discovery>>
  #kms_key_id = <<Optional value not found in discovery>>
  #kms_key_version_id = <<Optional value not found in discovery>>
  source        = "NONE"
  vm_cluster_id = oci_database_cloud_vm_cluster.export_dbsystem20220322041338.id
}

resource oci_database_database export_dbhome20220322041338_database {
  database {
    admin_password = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
    #backup_id = <<Optional value not found in discovery>>
    #backup_tde_password = <<Optional value not found in discovery>>
    character_set = "AL32UTF8"
    #database_software_image_id = <<Optional value not found in discovery>>
    #db_backup_config = <<Optional value not found in discovery>>
    db_name        = "aTFdb"
    db_unique_name = "aTFdb_sgx_iad"
    db_workload    = "OLTP"
    defined_tags = {
      "example-tag-namespace-all.example-tag" = "value"
    }
    freeform_tags = {
      "Department" = "Finance"
    }
    #kms_key_id = <<Optional value not found in discovery>>
    #kms_key_version_id = <<Optional value not found in discovery>>
    ncharacter_set = "AL16UTF16"
    #pdb_name = <<Optional value not found in discovery>>
    sid_prefix = "aTFdb"
    #tde_wallet_password = <<Optional value not found in discovery>>
    #vault_id = <<Optional value not found in discovery>>
  }
  db_home_id = oci_database_db_home.export_dbhome20220322041338.id
  #db_version = <<Optional value not found in discovery>>
  #kms_key_id = <<Optional value not found in discovery>>
  #kms_key_migration = <<Optional value not found in discovery>>
  #kms_key_rotation = <<Optional value not found in discovery>>
  #kms_key_version_id = <<Optional value not found in discovery>>
  source = "NONE" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  #vault_id = <<Optional value not found in discovery>>

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [source, database[0].admin_password]
  }
}

resource oci_database_db_home export_dbhome20220315041741 {
  #database = <<Optional value not found in discovery>>
  #database_software_image_id = <<Optional value not found in discovery>>
  #db_system_id = <<Optional value not found in discovery>>
  db_version = "12.1.0.2"
  defined_tags = {
    "example-tag-namespace-all.example-tag" = "value"
  }
  display_name = "dbhome20220315041741"
  freeform_tags = {
    "Department" = "Finance"
  }
  #is_desupported_version = <<Optional value not found in discovery>>
  #kms_key_id = <<Optional value not found in discovery>>
  #kms_key_version_id = <<Optional value not found in discovery>>
  source        = "NONE"
  vm_cluster_id = oci_database_cloud_vm_cluster.export_dbsystem20220315041741.id
}

resource oci_database_database export_dbhome20220315041741_database {
  database {
    admin_password = "<placeholder for missing required attribute>" #Required attribute not found in discovery, placeholder value set to avoid plan failure
    #backup_id = <<Optional value not found in discovery>>
    #backup_tde_password = <<Optional value not found in discovery>>
    character_set = "AL32UTF8"
    #database_software_image_id = <<Optional value not found in discovery>>
    #db_backup_config = <<Optional value not found in discovery>>
    db_name        = "aTFdb"
    db_unique_name = "aTFdb_74s_iad"
    db_workload    = "OLTP"
    defined_tags = {
      "example-tag-namespace-all.example-tag" = "value"
    }
    freeform_tags = {
      "Department" = "Finance"
    }
    #kms_key_id = <<Optional value not found in discovery>>
    #kms_key_version_id = <<Optional value not found in discovery>>
    ncharacter_set = "AL16UTF16"
    #pdb_name = <<Optional value not found in discovery>>
    sid_prefix = "aTFdb"
    #tde_wallet_password = <<Optional value not found in discovery>>
    #vault_id = <<Optional value not found in discovery>>
  }
  db_home_id = oci_database_db_home.export_dbhome20220315041741.id
  #db_version = <<Optional value not found in discovery>>
  #kms_key_id = <<Optional value not found in discovery>>
  #kms_key_migration = <<Optional value not found in discovery>>
  #kms_key_rotation = <<Optional value not found in discovery>>
  #kms_key_version_id = <<Optional value not found in discovery>>
  source = "NONE" #Required attribute not found in discovery, placeholder value set to avoid plan failure
  #vault_id = <<Optional value not found in discovery>>

  # Required attributes that were not found in discovery have been added to lifecycle ignore_changes
  # This is done to avoid terraform plan failure for the existing infrastructure
  lifecycle {
    ignore_changes = [database[0].admin_password, source]
  }
}

