Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/centos-7.2"
  c.vm.hostname = "managed-server-centos-72"
  c.vm.network(:forwarded_port, {:guest=>8080, :host=>80})
  c.vm.network(:private_network, {:ip=>"192.168.33.35"})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
  end
end
