// Copyright (c) 2017, 2024, Oracle and/or its affiliates. All rights reserved.
// Licensed under the Mozilla Public License v2.0

package database_tools_runtime

import "github.com/oracle/terraform-provider-oci/internal/tfresource"

func RegisterResource() {
	tfresource.RegisterResource("oci_database_tools_runtime_database_tools_connection_credential", DatabaseToolsRuntimeDatabaseToolsConnectionCredentialResource())
	tfresource.RegisterResource("oci_database_tools_runtime_database_tools_connection_credential_execute_grantee", DatabaseToolsRuntimeDatabaseToolsConnectionCredentialExecuteGranteeResource())
	tfresource.RegisterResource("oci_database_tools_runtime_database_tools_connection_credential_public_synonym", DatabaseToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonymResource())
	tfresource.RegisterResource("oci_database_tools_runtime_database_tools_connection_property_set", DatabaseToolsRuntimeDatabaseToolsConnectionPropertySetResource())
	tfresource.RegisterResource("oci_database_tools_runtime_database_tools_database_api_gateway_config_global", DatabaseToolsRuntimeDatabaseToolsDatabaseApiGatewayConfigGlobalResource())
	tfresource.RegisterResource("oci_database_tools_runtime_database_tools_database_api_gateway_config_pool", DatabaseToolsRuntimeDatabaseToolsDatabaseApiGatewayConfigPoolResource())
	tfresource.RegisterResource("oci_database_tools_runtime_database_tools_database_api_gateway_config_pool_api_spec", DatabaseToolsRuntimeDatabaseToolsDatabaseApiGatewayConfigPoolApiSpecResource())
	tfresource.RegisterResource("oci_database_tools_runtime_database_tools_database_api_gateway_config_pool_auto_api_spec", DatabaseToolsRuntimeDatabaseToolsDatabaseApiGatewayConfigPoolAutoApiSpecResource())
}
