// Copyright (c) 2017, 2024, Oracle and/or its affiliates. All rights reserved.
// Licensed under the Mozilla Public License v2.0

package database_tools_runtime

import "github.com/oracle/terraform-provider-oci/internal/tfresource"

func RegisterDatasource() {
	tfresource.RegisterDatasource("oci_database_tools_runtime_database_tools_connection_credential", DatabaseToolsRuntimeDatabaseToolsConnectionCredentialDataSource())
	tfresource.RegisterDatasource("oci_database_tools_runtime_database_tools_connection_credential_execute_grantee", DatabaseToolsRuntimeDatabaseToolsConnectionCredentialExecuteGranteeDataSource())
	tfresource.RegisterDatasource("oci_database_tools_runtime_database_tools_connection_credential_execute_grantees", DatabaseToolsRuntimeDatabaseToolsConnectionCredentialExecuteGranteesDataSource())
	tfresource.RegisterDatasource("oci_database_tools_runtime_database_tools_connection_credential_public_synonym", DatabaseToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonymDataSource())
	tfresource.RegisterDatasource("oci_database_tools_runtime_database_tools_connection_credential_public_synonyms", DatabaseToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonymsDataSource())
	tfresource.RegisterDatasource("oci_database_tools_runtime_database_tools_connection_credentials", DatabaseToolsRuntimeDatabaseToolsConnectionCredentialsDataSource())
	tfresource.RegisterDatasource("oci_database_tools_runtime_database_tools_connection_property_set", DatabaseToolsRuntimeDatabaseToolsConnectionPropertySetDataSource())
	tfresource.RegisterDatasource("oci_database_tools_runtime_database_tools_connection_user_credential", DatabaseToolsRuntimeDatabaseToolsConnectionUserCredentialDataSource())
	tfresource.RegisterDatasource("oci_database_tools_runtime_database_tools_connection_user_credentials", DatabaseToolsRuntimeDatabaseToolsConnectionUserCredentialsDataSource())
	tfresource.RegisterDatasource("oci_database_tools_runtime_database_tools_database_api_gateway_config_advanced_properties", DatabaseToolsRuntimeDatabaseToolsDatabaseApiGatewayConfigAdvancedPropertiesDataSource())
	tfresource.RegisterDatasource("oci_database_tools_runtime_database_tools_database_api_gateway_config_content", DatabaseToolsRuntimeDatabaseToolsDatabaseApiGatewayConfigContentDataSource())
	tfresource.RegisterDatasource("oci_database_tools_runtime_database_tools_database_api_gateway_config_global", DatabaseToolsRuntimeDatabaseToolsDatabaseApiGatewayConfigGlobalDataSource())
	tfresource.RegisterDatasource("oci_database_tools_runtime_database_tools_database_api_gateway_config_pool", DatabaseToolsRuntimeDatabaseToolsDatabaseApiGatewayConfigPoolDataSource())
	tfresource.RegisterDatasource("oci_database_tools_runtime_database_tools_database_api_gateway_config_pool_api_spec", DatabaseToolsRuntimeDatabaseToolsDatabaseApiGatewayConfigPoolApiSpecDataSource())
	tfresource.RegisterDatasource("oci_database_tools_runtime_database_tools_database_api_gateway_config_pool_api_specs", DatabaseToolsRuntimeDatabaseToolsDatabaseApiGatewayConfigPoolApiSpecsDataSource())
	tfresource.RegisterDatasource("oci_database_tools_runtime_database_tools_database_api_gateway_config_pool_auto_api_spec", DatabaseToolsRuntimeDatabaseToolsDatabaseApiGatewayConfigPoolAutoApiSpecDataSource())
	tfresource.RegisterDatasource("oci_database_tools_runtime_database_tools_database_api_gateway_config_pool_auto_api_specs", DatabaseToolsRuntimeDatabaseToolsDatabaseApiGatewayConfigPoolAutoApiSpecsDataSource())
	tfresource.RegisterDatasource("oci_database_tools_runtime_database_tools_database_api_gateway_config_pools", DatabaseToolsRuntimeDatabaseToolsDatabaseApiGatewayConfigPoolsDataSource())
}
