// Copyright (c) 2017, 2024, Oracle and/or its affiliates. All rights reserved.
// Licensed under the Mozilla Public License 2.0

variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "region" {}
variable "compartment_ocid" {}
variable "data_safe_target_ocid" {}
variable "target_database_user_name" {}

variable "target_database_password" {
  sensitive = true
}

provider "oci" {
  tenancy_ocid     = var.tenancy_ocid
  user_ocid        = var.user_ocid
  fingerprint      = var.fingerprint
  private_key_path = var.private_key_path
  region           = var.region
}

resource "oci_data_safe_masking_policy" "test_masking_policy" {
  compartment_id = var.compartment_ocid

  column_source {
    column_source = "TARGET"
    target_id     = var.data_safe_target_ocid
  }
}

resource "oci_data_safe_masking_policies_masking_column" "test_masking_column" {
  column_name       = "EMAIL"
  masking_policy_id = oci_data_safe_masking_policy.test_masking_policy.id
  object            = "EMPLOYEES"
  schema_name       = "HR_TEST"

  masking_formats {
    format_entries {
      type         = "FIXED_STRING"
      fixed_string = "MASKED_EMAIL"
    }
  }
}

resource "oci_data_safe_subsetting_policy" "test_subsetting_policy" {
  compartment_id    = var.compartment_ocid
  masking_policy_id = oci_data_safe_masking_policy.test_masking_policy.id

  schema_source {
    schema_source          = "TARGET"
    schemas_for_subsetting = ["HR_TEST"]
    target_id              = var.data_safe_target_ocid
  }

  depends_on = [oci_data_safe_masking_policies_masking_column.test_masking_column]
}

resource "oci_data_safe_subsetting_policy_subsetting_rule" "test_subsetting_rule" {
  subsetting_policy_id = oci_data_safe_subsetting_policy.test_subsetting_policy.id

  scope {
    schema_name = "HR_TEST"
    scope_type  = "SPECIFIC"
    object      = "EMPLOYEES"
  }

  subset_rule_entry {
    rule_type = "PERCENT"
    percent   = 10
  }
}

# Starts subsetting with masking enabled. The subsetting and masking reports
# are generated by the service as part of the jobs.
resource "oci_data_safe_subset_data" "test_subset_data" {
  subsetting_policy_id = oci_data_safe_subsetting_policy.test_subsetting_policy.id
  target_id            = var.data_safe_target_ocid
  masking              = "ENABLED"

  target_credentials {
    user_name = var.target_database_user_name
    password  = var.target_database_password
  }

  depends_on = [oci_data_safe_subsetting_policy_subsetting_rule.test_subsetting_rule]
}

data "oci_data_safe_subsetting_reports" "test_subsetting_reports" {
  compartment_id       = var.compartment_ocid
  subsetting_policy_id = oci_data_safe_subsetting_policy.test_subsetting_policy.id
  target_id            = var.data_safe_target_ocid

  depends_on = [oci_data_safe_subset_data.test_subset_data]
}

data "oci_data_safe_subsetting_report" "test_subsetting_report" {
  subsetting_report_id = data.oci_data_safe_subsetting_reports.test_subsetting_reports.subsetting_report_collection.0.items.0.id

  depends_on = [data.oci_data_safe_subsetting_reports.test_subsetting_reports]
}
