## This configuration was generated by terraform-provider-oci

resource oci_load_balancer_load_balancer export_example_load_balancer {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "example-tag-namespace-all.example-tag" = "value"
  }
  display_name = "example_load_balancer"
  freeform_tags = {
    "Department" = "Finance"
  }
  ip_mode    = "IPV4"
  is_private = "false"
  network_security_group_ids = [
    "ocid1.networksecuritygroup.oc1.iad.aaaaaaaau5bxphahoe5b2slbicamavrqkkxvxegyxxevg7d52zszjjkwk5hq",
  ]
  #reserved_ips = <<Optional value not found in discovery>>
  shape = "flexible"
  shape_details {
    maximum_bandwidth_in_mbps = "100"
    minimum_bandwidth_in_mbps = "10"
  }
  subnet_ids = [
    "ocid1.subnet.oc1.iad.aaaaaaaahcqz55pidjjxjzudjhzchktjgcvrv7lridtenkqlder5cedhqfca",
    "ocid1.subnet.oc1.iad.aaaaaaaaew4izfgkjyybj3ab6yqpx6fupl52dx53psahcvsvi3h6bqjd6zfa",
  ]
}

